# Generated by Django 4.1.7 on 2023-03-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_rename_user_id_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
