# Generated by Django 4.1.7 on 2023-03-23 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_remove_customer_application2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renteditems',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='renteditems',
            old_name='user_id',
            new_name='user',
        ),
    ]
