# Generated by Django 4.1.7 on 2023-03-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0011_alter_cart_user_alter_customer_usr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renteditems',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
