# Generated by Django 4.1.7 on 2023-03-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0012_renteditems_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renteditems',
            name='payment',
        ),
        migrations.AddField(
            model_name='renteditems',
            name='preview',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='renteditems',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
