# Generated by Django 4.1.7 on 2023-03-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0013_remove_renteditems_payment_renteditems_preview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renteditems',
            old_name='preview',
            new_name='total_amount',
        ),
    ]
