# Generated by Django 4.1.7 on 2023-03-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0014_rename_preview_renteditems_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='net_pay',
            field=models.IntegerField(null=True),
        ),
    ]
