# Generated by Django 4.1.7 on 2023-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0016_remove_customer_monthly_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lender_score',
            field=models.IntegerField(null=True),
        ),
    ]
