# Generated by Django 4.1.7 on 2023-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0017_customer_lender_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lender_score',
            field=models.FloatField(null=True),
        ),
    ]
