# Generated by Django 4.1.7 on 2023-03-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0018_alter_customer_lender_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_amount_dis',
            field=models.FloatField(null=True),
        ),
    ]
