# Generated by Django 4.1.7 on 2023-03-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0019_customer_total_amount_dis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='total_amount_dis',
        ),
        migrations.AddField(
            model_name='renteditems',
            name='total_amount_dis',
            field=models.FloatField(null=True),
        ),
    ]
